-- AlterTable
ALTER TABLE "User" ADD COLUMN     "allowAuto" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "budget" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "ratio" DOUBLE PRECISION NOT NULL DEFAULT 1;
