import tokenConfigs from './tokens.generated.json';

export type GmxV1IndexTokenConfig = {
  /** ERC-20 address emitted as `indexToken` by the GMX V1 Vault. */
  address: `0x${string}`;
  /** ERC-20 symbol read directly from the token contract. */
  tokenSymbol: string;
  /** Canonical underlying asset used by LuckyPlans pair labels. */
  assetSymbol: string;
  /** Canonical pair label used by historical trade records. */
  pair: `${string}/usd`;
  decimals: number;
  isWhitelisted: boolean;
  isStable: boolean;
  isShortable: boolean;
};

/**
 * Generated by GmxV1ConfigService from the Vault's historical token
 * enumeration at the configured end block. The Vault never removes an address
 * from `allWhitelistedTokens`, so this is a snapshot of all configured tokens,
 * including tokens that were later cleared.
 */
export const gmxV1IndexTokenConfigs = tokenConfigs as Record<
  number,
  Record<string, GmxV1IndexTokenConfig>
>;

export function getGmxV1IndexTokenConfig(
  chainId: number,
  indexToken: string,
): GmxV1IndexTokenConfig | undefined {
  return gmxV1IndexTokenConfigs[chainId]?.[indexToken.toLowerCase()];
}

export function resolveGmxV1Pair(chainId: number, indexToken: string): string {
  const tokenConfig = getGmxV1IndexTokenConfig(chainId, indexToken);

  if (!tokenConfig) {
    throw new Error(
      `Unknown GMX V1 index token ${indexToken.toLowerCase()} on chain ${chainId}. Regenerate the GMX V1 token snapshot before backfilling.`,
    );
  }

  return tokenConfig.pair;
}
