import { Candle } from '../types';

/**
 * Direction of a trade position
 */
export type TradeDirection = 'LONG' | 'SHORT';

/**
 * Signal generated by a SignalGenerator component
 * Signals only indicate entry direction - composer handles position logic
 */
export interface Signal {
  direction: TradeDirection;
  source: string;
  strength?: number;
  price: number;
  timestamp: number;
}

/**
 * Signal to exit a position
 */
export interface ExitSignal {
  reason: string;
  price: number;
  timestamp: number;
}

/**
 * Position size calculation result
 * Note: stopLoss is handled by StopLossExit component, not position sizer
 */
export interface PositionSize {
  quantity: number;
}

/**
 * Current open position
 * Note: stopLoss is handled by StopLossExit component
 */
export interface Position {
  direction: TradeDirection;
  entryPrice: number;
  entryTime: number;
  quantity: number;
}

/**
 * State shared across strategy components
 */
export interface StrategyState {
  position: Position | null;
  indicators: Map<string, any>;
  lastSignal: Signal | null;
  equity: number;
}

/**
 * Action returned by the strategy composer
 * Note: stopLoss is handled by StopLossExit component
 */
export interface TradeAction {
  type: 'ENTRY' | 'EXIT';
  direction?: TradeDirection;
  price: number;
  quantity?: number;
  reason?: string;
  signalSource?: string;
  timestamp: number;
}

/**
 * Signal Generator component interface
 * Produces entry signals indicating trade direction.
 * Signals only indicate direction - composer handles position management.
 */
export interface SignalGenerator {
  readonly name: string;

  /**
   * Process a candle and optionally generate an entry signal
   * @param candle The current candle
   * @param state The current strategy state
   * @returns A Signal with direction if entry conditions are met, null otherwise
   */
  processCandle(candle: Candle, state: StrategyState): Signal | null;

  /**
   * Reset the component to its initial state
   */
  reset(): void;
}

/**
 * Filter component interface
 * Confirms or rejects signals based on additional conditions
 */
export interface Filter {
  readonly name: string;

  /**
   * Check if a signal should be allowed to proceed
   * @param signal The signal to filter
   * @param candle The current candle
   * @param state The current strategy state
   * @returns true if signal should proceed, false to reject
   */
  shouldAllow(signal: Signal, candle: Candle, state: StrategyState): boolean;

  /**
   * Process a candle to update internal state
   * @param candle The current candle
   */
  processCandle(candle: Candle): void;

  /**
   * Reset the component to its initial state
   */
  reset(): void;
}

/**
 * Position Sizer component interface
 * Calculates position size (quantity) based on risk parameters.
 * Note: Stop loss is handled separately by StopLossExit component.
 */
export interface PositionSizer {
  readonly name: string;

  /**
   * Calculate position size and risk parameters
   * @param signal The entry signal
   * @param candle The current candle
   * @param state The current strategy state
   * @returns Position sizing parameters
   */
  calculateSize(
    signal: Signal,
    candle: Candle,
    state: StrategyState,
  ): PositionSize;
}

/**
 * Exit Condition component interface
 * Risk management handlers that can force position exits.
 * These are SPECIAL exit conditions (trailing stop, take profit, time-based, etc.)
 * NOT primary strategy logic - that belongs in SignalGenerator.
 */
export interface ExitCondition {
  readonly name: string;

  /**
   * Check if position should be exited
   * @param position The current open position
   * @param candle The current candle
   * @param state The current strategy state
   * @returns An ExitSignal if exit conditions are met, null otherwise
   */
  shouldExit(
    position: Position,
    candle: Candle,
    state: StrategyState,
  ): ExitSignal | null;

  /**
   * Process a candle to update internal state
   * @param candle The current candle
   */
  processCandle(candle: Candle): void;

  /**
   * Reset the component to its initial state
   */
  reset(): void;

  /**
   * Called when a new position is opened
   * Allows exits to initialize position-specific tracking
   * @param position The newly opened position
   */
  onPositionOpened?(position: Position): void;
}

/**
 * Component configuration for JSON strategy files
 */
export interface ComponentConfig {
  type: string;
  params: Record<string, any>;
}

/**
 * Strategy configuration structure
 */
export interface StrategyConfig {
  symbol: string;
  name: string;
  description?: string;
  signal: ComponentConfig;
  filters: ComponentConfig[];
  risk: ComponentConfig;
  exits: ComponentConfig[];
  settings?: {
    timeframe?: string;
    maxOpenPositions?: number;
    cooldownCandles?: number;
    capitalBase?: number;
  };
}
