import { Candle } from '../types';

/**
 * Direction of a trade position
 */
export type TradeDirection = 'LONG' | 'SHORT';

/**
 * Signal generated by a SignalGenerator component
 * Signals only indicate entry direction - composer handles position logic
 */
export interface Signal {
  direction: TradeDirection;
  source: string;
  strength?: number;
  price: number;
  timestamp: number;
}

/**
 * Signal to exit a position
 */
export interface ExitSignal {
  reason: string;
  price: number;
  timestamp: number;
}

/**
 * Position size calculation result
 * Note: stopLoss is handled by StopLossExit component, not position sizer
 */
export interface PositionSize {
  quantity: number;
  leverage: number; // Leverage multiplier (1 = no leverage)
  margin: number; // Actual margin to use (may be capped by available capital)
  notionalValue: number; // margin * leverage
  canOpen: boolean; // Whether enough capital is available to open
  requestedMargin: number; // Originally requested margin before capital check
  cappedByCapital: boolean; // Whether size was reduced due to capital limit
}

/**
 * Current open position
 * Note: stopLoss is handled by StopLossExit component
 */
export interface Position {
  direction: TradeDirection;
  entryPrice: number;
  entryTime: number;
  quantity: number;
  leverage: number; // Leverage multiplier (1 = no leverage)
  margin: number; // Collateral in USDT
  notionalValue: number; // margin * leverage
  liquidationPrice: number; // Price at which position is liquidated
}

/**
 * Result of opening a position through a platform
 */
export interface OpenPositionResult {
  adjustedEntryPrice: number; // Entry price after spread
  openingFee: number; // Fee paid to open position
  liquidationPrice: number; // Price at which position is liquidated
}

/**
 * Result of closing a position through a platform
 */
export interface ClosePositionResult {
  adjustedExitPrice: number; // Exit price after spread
  closingFee: number; // Fee paid to close position
  grossPnl: number; // PnL before fees
  netPnl: number; // PnL after fees
  pnlPercent: number; // PnL as percentage of margin
}

/**
 * Platform component interface
 * Handles fees, spread, and liquidation for perpetual futures simulation
 */
export interface Platform {
  readonly name: string;

  /**
   * Calculate costs and liquidation price for opening a position
   */
  calculateOpenPosition(
    direction: TradeDirection,
    entryPrice: number,
    notionalValue: number,
    leverage: number,
    margin: number,
  ): OpenPositionResult;

  /**
   * Calculate costs and PnL for closing a position
   */
  calculateClosePosition(
    position: Position,
    exitPrice: number,
  ): ClosePositionResult;

  /**
   * Check if a position should be liquidated based on candle price range
   */
  shouldLiquidate(
    position: Position,
    candleLow: number,
    candleHigh: number,
  ): { liquidated: boolean; liquidationPrice?: number };
}

/**
 * State shared across strategy components
 */
export interface StrategyState {
  position: Position | null;
  indicators: Map<string, any>;
  lastSignal: Signal | null;
  availableCapital: number; // Capital available for new positions
  lockedMargin: number; // Capital locked in current position
  realizedPnL: number; // Cumulative realized PnL
}

/**
 * Action returned by the strategy composer
 * Note: stopLoss is handled by StopLossExit component
 */
export interface TradeAction {
  type: 'ENTRY' | 'EXIT';
  direction?: TradeDirection;
  price: number;
  quantity?: number;
  reason?: string;
  signalSource?: string;
  timestamp: number;
  leverage?: number; // Leverage multiplier (1 = no leverage)
  margin?: number; // Collateral in USDT
  notionalValue?: number; // margin * leverage
}

/**
 * Signal Generator component interface
 * Produces entry signals indicating trade direction.
 * Signals only indicate direction - composer handles position management.
 */
export interface SignalGenerator {
  readonly name: string;

  /**
   * Process a candle and optionally generate an entry signal
   * @param candle The current candle
   * @param state The current strategy state
   * @returns A Signal with direction if entry conditions are met, null otherwise
   */
  processCandle(candle: Candle, state: StrategyState): Signal | null;

  /**
   * Reset the component to its initial state
   */
  reset(): void;
}

/**
 * Filter component interface
 * Confirms or rejects signals based on additional conditions
 */
export interface Filter {
  readonly name: string;

  /**
   * Check if a signal should be allowed to proceed
   * @param signal The signal to filter
   * @param candle The current candle
   * @param state The current strategy state
   * @returns true if signal should proceed, false to reject
   */
  shouldAllow(signal: Signal, candle: Candle, state: StrategyState): boolean;

  /**
   * Process a candle to update internal state
   * @param candle The current candle
   */
  processCandle(candle: Candle): void;

  /**
   * Reset the component to its initial state
   */
  reset(): void;
}

/**
 * Position Sizer component interface
 * Calculates position size (quantity) based on risk parameters.
 * Note: Stop loss is handled separately by StopLossExit component.
 */
export interface PositionSizer {
  readonly name: string;

  /**
   * Process a candle to update internal state (e.g., ATR for volatility-based sizers)
   * Called on every candle to keep indicators up to date.
   * Static sizers can implement this as a no-op.
   * @param candle The current candle
   */
  processCandle(candle: Candle): void;

  /**
   * Calculate position size and risk parameters
   * @param signal The entry signal
   * @param candle The current candle
   * @param state The current strategy state
   * @returns Position sizing parameters
   */
  calculateSize(
    signal: Signal,
    candle: Candle,
    state: StrategyState,
  ): PositionSize;

  /**
   * Reset the component to its initial state
   */
  reset(): void;
}

/**
 * Exit Condition component interface
 * Risk management handlers that can force position exits.
 * These are SPECIAL exit conditions (trailing stop, take profit, time-based, etc.)
 * NOT primary strategy logic - that belongs in SignalGenerator.
 */
export interface ExitCondition {
  readonly name: string;

  /**
   * Check if position should be exited
   * @param position The current open position
   * @param candle The current candle
   * @param state The current strategy state
   * @returns An ExitSignal if exit conditions are met, null otherwise
   */
  shouldExit(
    position: Position,
    candle: Candle,
    state: StrategyState,
  ): ExitSignal | null;

  /**
   * Process a candle to update internal state
   * @param candle The current candle
   */
  processCandle(candle: Candle): void;

  /**
   * Reset the component to its initial state
   */
  reset(): void;

  /**
   * Called when a new position is opened
   * Allows exits to initialize position-specific tracking
   * @param position The newly opened position
   */
  onPositionOpened?(position: Position): void;
}

/**
 * Component configuration for JSON strategy files
 */
export interface ComponentConfig {
  type: string;
  params: Record<string, any>;
}

/**
 * Strategy configuration structure
 */
export interface StrategyConfig {
  symbol: string;
  name: string;
  description?: string;
  signal: ComponentConfig;
  filters: ComponentConfig[];
  risk: ComponentConfig;
  exits: ComponentConfig[];
  platform: ComponentConfig; // Platform for fees/spread/liquidation (required)
  settings: {
    initialCapital: number; // Starting capital
  };
}
